import logging
from typing import List, Dict, Optional
from google import genai
from google.genai import types
from app.core.config import get_google_genai_config

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Store names - must match what's used in upload script
ECOMMERCE_STORE_NAME = "ecommerce-knowledge-store"
HEALTHCARE_STORE_NAME = "healthcare-knowledge-store"

class GoogleFileSearchRAG:
    """
    RAG system using Google's GenAI File Search (AQA - Attributed Question Answering).
    """
    
    def __init__(self, store_type: str = "healthcare"):
        """
        Initialize the Google File Search RAG system.
        
        Args:
            store_type: "healthcare" or "ecommerce"
        """
        self.api_key = get_google_genai_config()
        self.client = genai.Client(api_key=self.api_key)
        self.store_type = store_type
        self.store_name = HEALTHCARE_STORE_NAME if store_type == "healthcare" else ECOMMERCE_STORE_NAME
        self._store_resource_name = None

    @property
    def store_resource_name(self) -> Optional[str]:
        """Lazy load the store resource name by display name."""
        if self._store_resource_name:
            return self._store_resource_name
            
        logger.info(f"Looking for File Search Store: {self.store_name}")
        for store in self.client.file_search_stores.list():
            if store.display_name == self.store_name:
                self._store_resource_name = store.name
                logger.info(f"Found store: {store.name}")
                return self._store_resource_name
        
        logger.warning(f"Store '{self.store_name}' not found.")
        return None

    def query(self, query_text: str) -> str:
        """
        Query the Google File Search store.
        
        Args:
            query_text: The user's question.
            
        Returns:
            str: The answer generated by the model based on the files.
        """
        if not self.store_resource_name:
            return "Knowledge base not found. Please upload documents first."

        try:
            # Use the AQA model (or Gemini 1.5 Pro with file search tool)
            # For File Search, we typically use the `tools` argument with `google_search_retrieval` 
            # or `file_search` if using the specific API.
            # However, the `genai` library simplifies this.
            # We will use the `models.generate_content` with the store as a tool.
            
            tool = types.Tool(
                file_search_store=types.FileSearchStore(
                    file_search_store_name=self.store_resource_name
                )
            )

            response = self.client.models.generate_content(
                model="gemini-1.5-flash-002", # Or gemini-1.5-pro-002
                contents=query_text,
                config=types.GenerateContentConfig(
                    tools=[tool]
                )
            )
            
            return response.text

        except Exception as e:
            logger.error(f"Error querying Google File Search: {str(e)}")
            return f"Error processing your request: {str(e)}"

    def health_check(self) -> Dict:
        """Check if the store exists and is accessible."""
        try:
            store_name = self.store_resource_name
            return {
                "status": "healthy" if store_name else "not_configured",
                "store_name": self.store_name,
                "store_resource": store_name,
                "provider": "google_file_search"
            }
        except Exception as e:
            return {
                "status": "unhealthy",
                "error": str(e),
                "provider": "google_file_search"
            }

# Global instances
_healthcare_rag = None
_ecommerce_rag = None

def get_rag_system(store_type: str = "healthcare") -> GoogleFileSearchRAG:
    """Get the RAG system instance for the specified type."""
    global _healthcare_rag, _ecommerce_rag
    
    if store_type == "healthcare":
        if _healthcare_rag is None:
            _healthcare_rag = GoogleFileSearchRAG("healthcare")
        return _healthcare_rag
    elif store_type == "ecommerce":
        if _ecommerce_rag is None:
            _ecommerce_rag = GoogleFileSearchRAG("ecommerce")
        return _ecommerce_rag
    else:
        raise ValueError("Invalid store type. Must be 'healthcare' or 'ecommerce'.")

def get_medical_context(query: str) -> str:
    """Legacy wrapper for healthcare RAG."""
    rag = get_rag_system("healthcare")
    return rag.query(query)
